@ECHO OFF
ECHO Ayyy bone journo a-me a-piezan
ECHO you can mount CD ISO images like
ECHO      mount \path\to\image.iso
ECHO you can unmount all mounted disks like
ECHO      umount
ECHO you can mount floppy images like
ECHO      fmount /F:\path\to\image.img
ECHO and you can unmount all virtual floppies like
ECHO      fmount /u
ECHO For standard CD-ROM operations, use
ECHO      SHSUCDX
ECHO as a drop-in replacement for MSCDEX (same syntax)
ECHO you can get full details on using this
ECHO system by running the command
ECHO   MORENOTE
ECHO good luck, have fun, live long and prosper, love
